import { Inter } from "next/font/google";
import "./globals.css";
import Goi from "./components/TestApp/NO1/Goi";
import Goi2 from "./components/TestApp/NO2/Goi2";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Goi />
        <Goi2 />
      </body>
    </html>
  );
}
